name: Deploy to Cloudflare Pages on merge
on:
  push:
    branches:
      - release
jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"
      - run: pnpm install

  build_and_deploy:
    permissions:
      contents: read
      deployments: write
    needs: [cache-and-install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: blog
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
